### ISSUE TITLE
有偿求助：解分包小程序

### ISSUE THREAD

**Issue by yorick520** [leo9960/wechat-app-unpack#21]
有偿求助：分包小程序，请联系企鹅4971381

E:\wechat-by\wxappUnpacker-master\node_modules\vm2\lib\main.js:210
throw this._internal.Decontextify.value(e);
^
SyntaxError: Unexpected token }
at VMScript.compile (E:\wechat-by\wxappUnpacker-master\node_modules\vm2\lib
main.js:78:20)
at VM.run (E:\wechat-by\wxappUnpacker-master\node_modules\vm2\lib\main.js:20
4:52)
at wu.get.code (E:\wechat-by\wxappUnpacker-master\wuJs.js:28:6)
at ioLimit.runWithCb (E:\wechat-by\wxappUnpacker-master\wuLib.js:80:8)
at agent (E:\wechat-by\wxappUnpacker-master\wuLib.js:54:14)
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by leo9960** [comment]
请发包给1946682413
