### ISSUE TITLE
我怎么都解不了

### ISSUE THREAD

**Issue by liliang55** [leo9960/wechat-app-unpack#9]
我把微信数据打包了 ，解备份包后有很多已经浏览过的小程序，试着解包，解开了，但是就在wxml源码这里解不了，试了很多都不行！

**Comment by leo9960** [comment]
请问是哪个小程序？

**Comment by yorick520** [comment]
有偿求助：分包小程序，请联系企鹅4971381


E:\wechat-by\wxappUnpacker-master\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Unexpected token }
    at VMScript.compile (E:\wechat-by\wxappUnpacker-master\node_modules\vm2\lib\
main.js:78:20)
    at VM.run (E:\wechat-by\wxappUnpacker-master\node_modules\vm2\lib\main.js:20
4:52)
    at wu.get.code (E:\wechat-by\wxappUnpacker-master\wuJs.js:28:6)
    at ioLimit.runWithCb (E:\wechat-by\wxappUnpacker-master\wuLib.js:80:8)
    at agent (E:\wechat-by\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
